//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspDotNetMvcBusTicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TripId { get; set; }
        public string seatList { get; set; }
        public string UserId { get; set; }
        public string payment { get; set; }
        public string TransactionId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Trip tb_Trips { get; set; }
    }
}
