//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspDotNetMvcBusTicketReservation.Models
{
    using System;
    
    public partial class BookingListByUserId
    {
        public string RouteName { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public string TravelTime { get; set; }
        public string seatList { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public int BookingId { get; set; }
        public string payment { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    }
}
